# Generated by Django 4.1.6 on 2023-03-01 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
