# Generated by Django 4.1.6 on 2023-03-02 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
