# Generated by Django 4.1.6 on 2023-03-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_picture',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to='profile_images/'),
        ),
    ]
