# Generated by Django 4.1.6 on 2023-03-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_profile_picture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_picture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
